experiment_series: DLDLM_adaptation
experiment_id: dldlm_large_weighted_nllt_gibbs
experiments_directory_path: ./experiments/

random_seed: &random_seed 2307
mixed_precision: true
checkpoint_gradient: true

log_level: DEBUG
log_file: true

dldlm:
  model:
    pretrained: &pretrained ./experiments/DLDLM_pretraining/dldlm_large_2022_09_12_10_23_24/model/best_checkpoint
    kwargs:
      n_styles: &n_styles 16
      tf_size: 0
      init_tf_head: true
      context_pdrop: 0.0
      corruption_rate: 0.0
      kl_loss: false
      behaviour_loss: true
      sampling_loss: true
      behaviour_loss_weight: 0.001
      behaviour_loss_threshold: 0.125
      sampling_loss_weight: 0.1
      sampling_loss_threshold: 0.125
      tf_loss: false
    generate_kwargs:
      max_length: 512
      min_length: 1
      do_sample: true
      top_p: 1.0
      top_k: 0
      temperature: 0.7
  tokeniser:
    pretrained: *pretrained
    n_styles: *n_styles

optimizer:
  kwargs:
    lr: &lr 5.e-6
  n_epochs: 3
  max_gradient_norm: 1.0

lr_scheduler:
  lr: *lr
  lr_start: 0.0
  lr_stop: 0.0
  warmup: 0.05

alpha_scheduler: {}

beta_scheduler: {}

evaluation:
  monitored_metric: loss
  metrics:
    word_count:
      top_n: 20
    traces:
      window_size: 4
    sample_responses:
      n_samples: 10
    word_stats: {}

data:
  corpora_dir_path: ./resources/data/raw/
  cache_dir_path: ./resources/data/cache/
  kwargs:
    corpus_prefix: adaptation_corpus
    corpus_list:
      - HOPE_WSDM_2022
    latent_init: false
    max_context_length: 256
    max_response_length: 256
  splits:
    train:
      mini_batch_size: 32
      in_mem: 2
      n_workers: &n_workers 4
    validation:
      mini_batch_size: &eval_mini_batch_size 16
      in_mem: *eval_mini_batch_size
      n_workers: *n_workers
    test:
      mini_batch_size: *eval_mini_batch_size
      in_mem: *eval_mini_batch_size
      n_workers: *n_workers
